# Generated by Django 2.2 on 2021-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='last_checked_out_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_checked_out_date',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
    ]
