# Generated by Django 2.2 on 2021-05-16 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210516_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
